      - name: Install Podman
        run: sudo apt-get update && sudo apt-get install -y podman

      - name: Install Yamllint
        run: sudo apt-get install -y yamllint

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Lint YAML files
        run: yamllint .

      - name: Build image with Podman
        run: podman build -t flask-app .

      - name: Scan dependencies
        run: trivy fs .

      - name: Scan image
        run: trivy image localhost/flask-app
